apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cron
spec:
  # Executa a cada cinco horas
  schedule: "0 */5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-job
              image: my-batch-image
          restartPolicy: Never
