apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sources-volume-claim
  namespace: default
spec:
  resources:
    requests:
      storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: standard
