apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ghost
  template:
    metadata:
      labels:
        run: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:1.22.1
          #resources:
          #limits:
          #memory: "128Mi"
          #cpu: "500m"
          ports:
            - containerPort: 2368
          command:
            - "sh"
            - "-c"
            - "cp /ghost-config/ghost-config.js /var/lib/ghost/config.js && /usr/local/bin/docker-entrypoint.sh node current/index.js"
          volumeMounts:
            - mountPath: /ghost-config
              name: config
          imagePullPolicy: Always
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: ghost-config-mysql
