apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 27017
          name: peer
      command:
        - mongod
