apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        # redis
        - command: [sh, -c, source /redis-config/init.sh]
          image: redis:3.2.7-alpine
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - mountPath: /redis-config
              name: config
            - mountPath: /redis-data
              name: data
          imagePullPolicy: Always
        # sentinel
        - command: [sh, -c, source /redis-config/sentinel.sh]
          image: redis:3.2.7-alpine
          name: sentinel
          volumeMounts:
            - mountPath: /redis-config
              name: sentinel-config
          imagePullPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: redis-config
          name: config
        - emptyDir:
          name: data
        - name: sentinel-config
          hostPath:
            # directory location on host
            path: /data/redis-config
            # this field is optional
            type: Directory
