apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - command: [sh, -c, source /redis-config/init.sh]
          image: redis:3.2.7-alpine
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - mountPath: /redis-config
              name: config
            - mountPath: /redis-data
              name: data
          imagePullPolicy: Always
        - command: [sh, -c, source /redis-config/sentinel.sh]
          image: redis:3.2.7-alpine
          name: sentinel
          volumeMounts:
            - mountPath: /redis-config
              name: config
          imagePullPolicy: Always
      volumes:
        - configMap:
            #defaultMode: 420
            defaultMode: 0777
            name: redis-config
          name: config
        - name: data
          hostPath:
            # directory location on host
            path: /data
            # this field is optional
            type: DirectoryOrCreate
