apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: validating-controller.default
spec:
  groups:
    - system:authenticated
  request: REPLACEME
  usages:
    - digital signature
    - key encipherment
    - key agreement
    - server auth
  signerName: beta.kuar.com/eduardo
