apiVersion: v1
kind: Pod
metadata:
  name: test-app
  labels:
    hello: universe
spec:
  containers:
    - name: test-app
      image: ubuntu:jammy
      command: ["/bin/bash"]
      args: ["-c", "sleep infinity"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
